const faceList = [`/emoji/static/emoji/smile.webp`, `/emoji/static/emoji/tv/tv.webp`]

const emojiList: {}[] = [
  {
    '[口罩]': `/public/static/emoji/kouzhao.webp`,
    '[狗头]': `/public/static/emoji/goutou.webp`,
    '[微笑]': `/public/static/emoji/smile.webp`,
    '[大笑2]': `/public/static/emoji/daxiao2.png`,
    '[OK]': `/public/static/emoji/ok.webp`,
    '[星星眼]': `/public/static/emoji/star.webp`,
    '[辣眼睛]': `/public/static/emoji/layanjing.webp`,
    '[吃瓜]': `/public/static/emoji/chigua.webp`,
    '[滑稽]': `/public/static/emoji/huaji.webp`,
    '[呲牙]': `/public/static/emoji/teeth.webp`,
    '[打call]': `/public/static/emoji/dacall.webp`,
    '[喝酒]': `/public/static/emoji/hejiu.webp`,
    '[乖]': `/public/static/emoji/guai.webp`,
    '[吐舌]': `/public/static/emoji/tushe.webp`,
    '[汗]': `/public/static/emoji/han.webp`,
    '[大哭2]': `/public/static/emoji/daku.webp`,
    '[超赞]': `/public/static/emoji/chaozan.webp`,
    '[超开心]': `/public/static/emoji/chaokaixin.webp`,
    '[委屈]': `/public/static/emoji/weiqu.webp`,
    '[困狗]': `/public/static/emoji/kungou.webp`,
    '[藏狐]': `/public/static/emoji/zanghu.webp`,
    '[脸红]': `/public/static/emoji/lianhong.webp`,
    '[脱单doge]': `/public/static/emoji/doge.webp`,
    '[给心心]': `/public/static/emoji/heart.webp`,
    '[笑]': `/public/static/emoji/dx.webp`,
    '[哦呼]': `/public/static/emoji/oh.webp`,
    '[嫌弃]': `/public/static/emoji/xq.webp`,
    '[喜欢]': `/public/static/emoji/like.webp`,
    '[酸了]': `/public/static/emoji/sl.webp`,
    '[大哭]': `/public/static/emoji/dq.webp`,
    '[害羞]': `/public/static/emoji/hx.webp`,
    '[无语]': `/public/static/emoji/wy.webp`,
    '[疑惑]': `/public/static/emoji/yh.webp`,
    '[调皮]': `/public/static/emoji/tiaopi.webp`,
    '[笑哭]': `/public/static/emoji/xiaoku.webp`,
    '[奸笑]': `/public/static/emoji/jianxiao.webp`,
    '[偷笑]': `/public/static/emoji/touxiao.webp`,
    '[大笑]': `/public/static/emoji/daxiao.webp`,
    '[阴险]': `/public/static/emoji/yinxian.webp`,
    '[捂脸]': `/public/static/emoji/wulian.webp`,
    '[惊喜]': `/public/static/emoji/jingxi.webp`,
    '[惊讶]': `/public/static/emoji/jingya.webp`,
    '[捂脸哭]': `/public/static/emoji/wulianku.webp`,
    '[妙啊]': `/public/static/emoji/miaoa.webp`,
    '[鼓掌]': `/public/static/emoji/guzhang.webp`,
    '[尴尬]': `/public/static/emoji/ganga.webp`,
    '[冷]': `/public/static/emoji/cold.webp`,
    '[灵魂出窍]': `/public/static/emoji/linghunchuqiao.webp`,
    '[傲娇]': `/public/static/emoji/aojiao.webp`,
    '[疼]': `/public/static/emoji/teng.webp`,
    '[吓]': `/public/static/emoji/xia.webp`,
    '[生病]': `/public/static/emoji/shengbing.webp`,
    '[吐]': `/public/static/emoji/tu.webp`,
    '[嘘声]': `/public/static/emoji/xusheng.webp`,
    '[捂眼]': `/public/static/emoji/wuyan.webp`,
    '[思考]': `/public/static/emoji/sikao.webp`,
    '[再见]': `/public/static/emoji/zaijian.webp`,
    '[翻白眼]': `/public/static/emoji/fanbaiyan.webp`,
    '[哈欠]': `/public/static/emoji/haqian.webp`,
    '[奋斗]': `/public/static/emoji/fengdou.webp`,
    '[墨镜]': `/public/static/emoji/mojing.webp`,
    '[撇嘴]': `/public/static/emoji/piezui.webp`,
    '[难过]': `/public/static/emoji/nanguo.webp`,
    '[抓狂]': `/public/static/emoji/zhuakuang.webp`,
    '[生气]': `/public/static/emoji/shengqi.webp`,
    '[爱心]': `/public/static/emoji/aixin.webp`,
    '[胜利]': `/public/static/emoji/shengli.webp`,
    '[抱拳]': `/public/static/emoji/baoquan.webp`,
    '[保佑]': `/public/static/emoji/baoyou.webp`,
    '[支持]': `/public/static/emoji/zhichi.webp`
  },
  {
    '[tv_doge]': `/public/static/emoji/tv/doge.webp`,
    '[tv_坏笑]': `/public/static/emoji/tv/huaixiao.webp`,
    '[tv_难过]': `/public/static/emoji/tv/nanguo.webp`,
    '[tv_生气]': `/public/static/emoji/tv/shengqi.webp`,
    '[tv_委屈]': `/public/static/emoji/tv/weiqu.webp`,
    '[tv_斜眼笑]': `/public/static/emoji/tv/xieyanxiao.webp`,
    '[tv_呆]': `/public/static/emoji/tv/dai.webp`,
    '[tv_发怒]': `/public/static/emoji/tv/fanu.webp`,
    '[tv_惊吓]': `/public/static/emoji/tv/jingxia.webp`,
    '[tv_呕吐]': `/public/static/emoji/tv/outu.webp`,
    '[tv_思考]': `/public/static/emoji/tv/sikao.webp`,
    '[tv_微笑]': `/public/static/emoji/tv/weixiao.webp`,
    '[tv_疑问]': `/public/static/emoji/tv/yiwen.webp`,
    '[tv_大哭]': `/public/static/emoji/tv/daku.webp`,
    '[tv_鼓掌]': `/public/static/emoji/tv/guzhang.webp`,
    '[tv_抠鼻]': `/public/static/emoji/tv/koubi.webp`,
    '[tv_亲亲]': `/public/static/emoji/tv/qinqin.webp`,
    '[tv_调皮]': `/public/static/emoji/tv/tiaopi.webp`,
    '[tv_笑哭]': `/public/static/emoji/tv/xiaoku.webp`,
    '[tv_晕]': `/public/static/emoji/tv/yun.webp`,
    '[tv_点赞]': `/public/static/emoji/tv/dianzan.webp`,
    '[tv_害羞]': `/public/static/emoji/tv/haixiu.webp`,
    '[tv_睡着]': `/public/static/emoji/tv/shuizhe.webp`,
    '[tv_色]': `/public/static/emoji/tv/se.webp`,
    '[tv_吐血]': `/public/static/emoji/tv/tuxue.webp`,
    '[tv_无奈]': `/public/static/emoji/tv/wunai.webp`,
    '[tv_再见]': `/public/static/emoji/tv/zaijian.webp`,
    '[tv_流汗]': `/public/static/emoji/tv/liuhan.webp`,
    '[tv_偷笑]': `/public/static/emoji/tv/touxiao.webp`,
    '[tv_抓狂]': `/public/static/emoji/tv/zhuakuang.webp`,
    '[tv_黑人问号]': `/public/static/emoji/tv/wenhao.webp`,
    '[tv_困]': `/public/static/emoji/tv/kun.webp`,
    '[tv_打脸]': `/public/static/emoji/tv/dalian.webp`,
    '[tv_闭嘴]': `/public/static/emoji/tv/bizui.webp`,
    '[tv_鄙视]': `/public/static/emoji/tv/bishi.webp`,
    '[tv_腼腆]': `/public/static/emoji/tv/miantian.webp`,
    '[tv_馋]': `/public/static/emoji/tv/chan.webp`,
    '[tv_可爱]': `/public/static/emoji/tv/keai.webp`,
    '[tv_发财]': `/public/static/emoji/tv/facai.webp`,
    '[tv_生病]': `/public/static/emoji/tv/shengbing.webp`,
    '[tv_流鼻血]': `/public/static/emoji/tv/liubixue.webp`,
    '[tv_尴尬]': `/public/static/emoji/tv/ganga.webp`,
    '[tv_大佬]': `/public/static/emoji/tv/dalao.webp`,
    '[tv_流泪]': `/public/static/emoji/tv/liulei.webp`,
    '[tv_冷漠]': `/public/static/emoji/tv/lenmo.webp`,
    '[tv_皱眉]': `/public/static/emoji/tv/zhoumei.webp`,
    '[tv_鬼脸]': `/public/static/emoji/tv/guilian.webp`,
    '[tv_调侃]': `/public/static/emoji/tv/tiaokan.webp`,
    '[tv_目瞪口呆]': `/public/static/emoji/tv/mudengkoudai.webp`
  }
]

//把emojiList数组中的每一个对象，放到emojiMap中方便取用
function allEmoji(): {} {
  let emojiMap = {}
  emojiList.map(emojis => (emojiMap = { ...emojiMap, ...emojis }))
  return emojiMap
}

export default {
  faceList,
  emojiList,
  allEmoji: allEmoji()
}
